<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(DotNetVersion)</TargetFramework>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <!-- Common metadata properties for publishing -->
    <Description>C#/WinRT Runtime v$(VersionString)</Description>
    <AssemblyTitle>C#/WinRT Runtime v$(VersionString)</AssemblyTitle>
    <Copyright>Copyright (c) Microsoft Corporation. All rights reserved.</Copyright>
    <AssemblyVersion>$(AssemblyVersionNumber)</AssemblyVersion>
    <FileVersion>$(VersionNumber)</FileVersion>

    <!-- 'WindowsRuntime' is the root namespace, with the name being consistent with eg. 'System.Runtime.InteropServices.WindowsRuntime' -->
    <RootNamespace>WindowsRuntime</RootNamespace>
      
    <!--
      The assembly name must always be 'WinRT.Runtime', as other components have a dependency on
      the exact .dll name. For instance, the UWP XAML compiler special cases 'WinRT.Runtime.dll'.
    -->
    <AssemblyName>WinRT.Runtime</AssemblyName>

    <!-- Ignore warnings for '[Obsolete]' members that are a private implementation detail (since they're allowed here) -->
    <NoWarn>$(NoWarn);CSWINRT3001</NoWarn>

    <!-- Enable strong name signing -->
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>key.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
    
  <!--
    Emit the [SupportedOSVersion] attribute if needed. Note that the .NET SDK already emits this attribute
    automatically, but only when targeting the Windows TFM. So here we're manually including it instead.
  -->
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.Versioning.SupportedOSPlatformAttribute">
      <_Parameter1>windows6.3</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <!-- Import all .tt files with their generated .g.cs files (the T4 service is imported in the .props file) -->
  <ItemGroup>
    <None Update="**\*.tt">
      <LastGenOutput>%(Filename).g.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <Compile Update="**\*.g.cs">
      <DependentUpon>$([System.IO.Path]::GetFileNameWithoutExtension('%(Filename)')).tt</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>
  
  <!-- T4 template generation service (the .tt/.g.cs files are resolved in the .targets file) -->
  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>
</Project>
